---
name: Runner Debug

on:
  workflow_dispatch:

jobs:
  # runner-rhos01-rhel93:
  #   runs-on: [kite, x86_64, rhos-01, rhel-9-3, large]
  #   steps:
  #     - name: Show all environment variables
  #       run: printenv
  #     - name: Show system info
  #       run: cat /etc/os-release
  #     - name: Show system arch
  #       run: |
  #         uname -a
  #         lscpu
  #         free -mh

  # runner-gcp-cs9:
  #   runs-on: [kite, x86_64, gcp, centos-stream-9, large]
  #   steps:
  #     - name: Show all environment variables
  #       run: printenv
  #     - name: Show system info
  #       run: cat /etc/os-release
  #     - name: Show system arch
  #       run: |
  #         uname -a
  #         lscpu
  #         free -mh

  # gcp-runner-fedora-38:
  #   runs-on: [kite, x86_64, gcp, fedora-38, medium]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Show all environment variables
  #       run: printenv
  #     - name: Show system info
  #       run: cat /etc/os-release
  #     - name: Show system arch
  #       run: |
  #         uname -a
  #         lscpu
  #         free -mh
  #         sleep 2h

  gcp-runner-fedora-38:
    runs-on: [kite, x86_64, gcp, fedora-38, medium]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: virt-s1/rhel-edge

      - run: ./ostree-raw-image.sh
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  # gcp-runner-fedora-37:
  #   runs-on: [kite, x86_64, gcp, fedora-37, medium]
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Show all environment variables
  #       run: printenv
  #     - name: Show system info
  #       run: cat /etc/os-release
  #     - name: Show system arch
  #       run: |
  #         uname -a
  #         lscpu
  #         free -mh

  # runner-beaker-arm:
  #   runs-on: [kite, aarch64, beaker, fedora-37]
  #   steps:
  #     - name: Show all environment variables
  #       run: printenv

  # runner-beaker-arm-vm:
  #   runs-on: [kite, aarch64, beaker-vm, rhel-9-3]
  #   steps:
  #     - name: Show all environment variables
  #       run: printenv
  #     - name: Show system info
  #       run: cat /etc/os-release
  #     - name: Show system arch
  #       run: |
  #         uname -a
  #         lscpu
  #         free -mh

  # runner-container-1:
  #   runs-on: container-runner
  #   container: quay.io/fedora/fedora:38-x86_64
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Show all environment variables
  #       run: printenv

  # runner-container-2:
  #   runs-on: container-runner
  #   container:
  #     image: quay.io/fedora/fedora:38-x86_64
  #   steps:
  #     - name: Show all environment variables
  #       run: |
  #         printenv
  #         curl -h
