---
name: Trigger Hub of All Tests

on:
  repository_dispatch:
    types: [test, build]
  schedule:
    - cron: '5 2 * * *'

jobs:
  rhel-9-0:
    if: ${{ github.event.schedule != '5 2 * * *' ||
            (github.event.event_type == 'build' && contains(github.event.client_payload.distro, 'rhel-9-0')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare Edge Container image build PR
        run: date "+%F %R" >> rhel-9-0-image-build.log

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Setup ${{ steps.date.outputs.date }} RHEL 9.0 ostree repo"
          committer: cloudkitebot <henrywangxf1@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: cpr
          delete-branch: true
          title: "Setup ${{ steps.date.outputs.date }} RHEL 9.0 ostree repo"
          body: |
            Setup RHEL 9.0 ostree repo
            - Date - ${{ steps.date.outputs.date }}
            - Running on http://edge-rhel-9-0-normal-virt-qe-3rd.apps.ocp4.prod.psi.redhat.com/repo/refs/heads/rhel/9/x86_64/edge

      - name: Add a comment to trigger build workflow
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: /build-rhel-9-0

      - name: Create a project card to track build result
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{ secrets.PAT }}
          project-name: Build OSTree Repo
          column-name: RHEL-9-0
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
