---
name: Trigger hub of setup ostree repo

on:
  repository_dispatch:
    types: [build]
  schedule:
    - cron: '5 2 * * *'

jobs:
  pr-info:
    runs-on: ubuntu-latest
    steps:
      - name: Query author repository permissions
        uses: octokit/request-action@v2.x
        id: user_permission
        with:
          route: GET /repos/${{ github.repository }}/collaborators/${{ github.event.sender.login }}/permission
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # restrict running of tests to users with admin or write permission for the repository
      # see https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#get-repository-permissions-for-a-user
      # store output if user is allowed in allowed_user job output so it has to be checked in downstream job
      - name: Check if user does have correct permissions
        if: contains('admin write', fromJson(steps.user_permission.outputs.data).permission)
        id: check_user_perm
        run: |
          echo "User '${{ github.event.sender.login }}' has permission '${{ fromJson(steps.user_permission.outputs.data).permission }}' allowed values: 'admin', 'write'"
          echo "::set-output name=allowed_user::true"

    outputs:
      allowed_user: ${{ steps.check_user_perm.outputs.allowed_user }}

  rhel-9-0:
    needs: pr-info
    if: ${{ needs.pr-info.outputs.allowed_user == 'true' && (github.event.schedule == '5 2 * * *' || contains(github.event.client_payload.distro, 'rhel-9-0')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Prepare Edge Container image build PR
        run: date "+%F %R" >> rhel-9-0-image-build.log

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Setup RHEL 9.0 ostree repo on ${{ steps.date.outputs.date }}"
          committer: cloudkitebot <henrywangxf1@gmail.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: cpr
          branch-suffix: random
          delete-branch: true
          title: "OSTree Repo - ${{ steps.date.outputs.date }}"
          body: |
            Setup RHEL 9.0 ostree repo
            - Date: ${{ steps.date.outputs.date }}
            - Commit URL: http://edge-rhel-9-0-normal-virt-qe-3rd.apps.ocp4.prod.psi.redhat.com/repo/refs/heads/rhel/9/x86_64/edge

      - name: Add a comment to trigger build workflow
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.PAT }}
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
          body: /build-rhel-9-0

      - name: Create a project card to track build result
        uses: peter-evans/create-or-update-project-card@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          project-name: Build OSTree Repo
          column-name: RHEL-9-0
          issue-number: ${{ steps.cpr.outputs.pull-request-number }}
